const puppeteer = require('puppeteer');
const findContactPoints = require('./scrapeGoogleLinks.js').findContactPoints;
(async () => {
    let current = 0;

    const results = {};

    //Set protocolTimeout to infinite
    const browser = await puppeteer.launch({
        headless: false,
        args: ['--disable-features=site-per-process'],
        timeout: 0
    });
    const page = await browser.newPage();

    //Set all timeouts to 0
    page.setDefaultNavigationTimeout(0);
    page.setDefaultTimeout(0);

    await page.setViewport({ width: 1536, height: 730 });


    async function scrapeCurrentURLs() {
        const names = [
            "Cantina Feliz",
            "Zakes Cafe",
            "Bridgets Steakhouse",
            "Scoogis Italian Kitchen & Bar",
            "Gypsy Blu",
            "Dettera Restaurant & Wine Bar",
            "FROM THE BOOT",
            "Forest & Main Brewing Company",
            "El Limon Ambler",
            "Fireside Bar & Grille",
            "Magerk's Pub, Fort Washington",
            "Saffron Indian Kitchen",
            "Palace of Asia",
            "KC's Alley",
            "Little Italy Pizza",
            "Oreland Pizza",
            "Rich's Delicatessen",
            "Penn Restaurant",
            "Jade Garden",
            "PrimoHoagies",
            "Sweet Briar Cafe and Ice Cream",
            "Planchette Bistro and Creperie",
            "Julia's on the Go",
            "The Flour Pot Cookies",
            "Sushi Hatsu",
            "Fill A Bagel & Breads - Oreland",
            "LaScala's Fire Upper Dublin",
            "Wawa",
            "Mama's Pizza IV",
            "Lucianis Brick Oven Pizzeria",
            "Tamarindos",
            "Costa Deli",
            "Po Le Cucina",
            "Golden House Restaurant",
            "KUB KAO Thai",
            "Jarrettown Hotel",
            "Bubbakoo's Burritos",
            "McDonald's",
            "Pie and Plate Cafe",
            "Redstone American Grill – Upper D...",
            "Dresher Deli",
            "Rice & Curry I Thai & Asian Bis...",
            "Oreland Inn",
            "Sum Pig",
            "La Provence",
            "Maple Glen Tavern",
            "Ambler Beverage Exchange",
            "Chipotle Mexican Grill",
            "La Cucina Fanti",
            "Giuseppe's of Ambler",
            "Ooka Japanese Restaurant",
            "Bonefish Grill",
            "Sushi House",
            "Señor Salsa",
            "The Cheesecake Factory",
            "Tonelli's Pizza Pub",
            "Pasta Fazool",
            "Vintage Bar And Grill",
            "Miller's Ale House",
            "Ooka sushi.hibachi steak house",
            "La Strada Italian Restaurant",
            "Palz Tap House",
            "Tin Pan Alley Tavern",
            "Sam���s Italian Market and Bake...",
            "Nino's Pizzarama - Willow Grove",
            "Big Chief Brewing",
            "Carrabba's Italian Grill",
            "Roman Delight",
            "ASIAN TASTE INN",
            "La Morena Hatboro",
            "MING'S RESTAURANT",
            "New Wild Ginger",
            "QDOBA Mexican Eats",
            "Anthony's Coal Fired Pizza & Wi...",
            "Da Bistro Mediterranean Grill",
            "Ricardo's Restaurant",
            "Hatboro Dish",
            "Vic Sushi & Thai Cuisine",
            "Chipotle Mexican Grill",
            "Be Well Bakery & Cafe",
            "Chipotle Mexican Grill",
            "Ban Ban Asian Bistro",
            "China Garden Inn Restaurant",
            "corner bakery cafe",
            "Joe's Pizza",
            "Yummi Yummi Chinese Restaurant",
            "Ben & Irv's",
            "Terminal Restaurant",
            "Panera Bread",
            "Heritage Hoagies",
            "Lochel's Bakery",
            "Mr P Pizza & Pasta",
            "Bonnet Lane Family Restaurant",
            "Bistro Albertino",
            "Silvermoon Pizzeria Restaurant",
            "Haagen-Dazs",
            "Lee's Hoagie House",
            "Panda Bistro",
            "Riviera D'Italia",
            "Gummlai Thai",
            "Iron Hill Brewery & Restaurant",
            "Trolley Car Diner",
            "Valley Green Inn",
            "Chili's Grill & Bar",
            "CinCin Restaurant",
            "Cake",
            "Bredenbeck's Bakery",
            "UNION JACKS OLDE GLORY PUB",
            "Takka Grill & Shrimpies",
            "Tiffin Indian Cuisine Mt Airy",
            "Keswick Tavern",
            "McMenamin's Tavern",
            "Food From the Heart",
            "Jamil's Cafe",
            "Trevi",
            "McNally's Tavern Chestnut Hill",
            "STARBUCKS COFFEE",
            "el poquito",
            "Richman's Ice Cream & Burger Co.",
            "New South Ocean Chinese & Japanese ...",
            "Bacio Italian Cucina",
            "Thai Kuu Restaurant",
            "Jamaican D S Jerk Chicken",
            "Fairlane Grill",
            "Mt Airy Breakfast & Lunch",
            "Chestnut Grill and Sidewalk Cafe",
            "June's Restaurant",
            "Movie Tavern Flourtown",
            "Mount Airy Breakfast Boutique",
            "Breakfast Boutique Chestnut Hill",
            "Yummy House Chinese & American ...",
            "Bahia Bowls Chestnut Hill",
            "Trios Tomato Pie",
            "Jyoti Indian Bistro",
            "Chestnut Hill Coffee Company",
            "The Village Diner",
            "Royal's Restaurant",
            "Brewers Outlet Of Mt. Airy & Chestn...",
            "Humpty's Dumplings",
            "Chicko Tako",
            "Michael's Family Restaurant",
            "Panda Garden",
            "Malelani Cafe",
            "Moonlight Family Diner",
            "Brunos",
            "Hokka Hokka Japanese Restaurant",
            "Jasmine Asian Bistro",
            "TAVERN ON THE HILL",
            "Wawa",
            "Fiesta Pizza III",
            "Cafe Soho",
            "Steve's Prince Of Steaks",
            "El Balconcito II",
            "Austrian Village Bar & Restaura...",
            "Chuck's Alibi",
            "Marco Polo Ristorante & Bar",
            "West Ave Grille Restaurant & Food T...",
            "Marzano Ristorante",
            "DuBu",
            "Gaul & Co. Malt House Rockledge",
            "The Red Rooster Inn",
            "The Shake Seafood",
            "Kings Corner",
            "The Drake Tavern",
            "Little Caesars",
            "4 Every Occasion Cakes & Cupcak...",
            "The Cheesecake Lady",
            "Northeast Sandwich Co.",
            "1910 Bar & Grille",
            "Krush Lounge",
            "QDOBA Mexican Eats",
            "Mr Sushi",
            "Moonstruck",
            "Rieker's Prime Meats",
            "Ipanema Sports Bar And Grill",
            "Iron Hill Brewery",
            "Pita Pocket Eatery",
            "More Food Court",
            "Tiffin Indian Cuisine Elkins Pa...",
            "White Elephant Restaurant",
            "Quaker Diner",
            "Chase's Hop Shop",
            "Espresso Cafe & Sushi Bar",
            "New Olympia House",
            "Jules Thin Crust",
            "Sangkee Asian Kitchen",
            "Country Club Diner",
            "The Flavor Spot",
            "Yong Hwa Roo",
            "Asia Express",
            "Outback Steakhouse",
            "No. 1 House",
            "China King",
            "Larry's Steaks & Hoagies",
            "Hibachi Of Jenkintown",
            "Wawa",
            "Main Street Pizzeria & Grille",
            "Gaeta's Tomato Pies",
            "Paris Baguette",
            "Mario Brothers Pizza",
            "Uzbekistan Restaurant",
            "Suburban Diner Restaurant",
            "Ninja Japanese Restaurant",
            "Samarkand",
            "Cafe Michelangelo",
            "Toscana 52 (food & Bar Takeout With...",
            "Golden Gates Restaurant",
            "Osteria Saporino Byob",
            "Trev's Philly Steaks",
            "The Churchville Inn",
            "Sweeney's Station Saloon",
            "Fireside Inn",
            "Las Margaritas",
            "The Iron Oven",
            "Maggio's",
            "Miss Philly Grill",
            "osaka504",
            "STEAM",
            "Kopper Kettle Tavern",
            "Panera Bread",
            "Erwin's Country Kitchen",
            "2nd Street Bagels",
            "Mt Fuji Japanese Food & Steak",
            "Peppe's Mexican Grill",
            "Happy Star Restaurant",
            "Da Vinci's Brick Oven Pizzeria",
            "Longhitano's Pizza",
            "Hong Kong King Buffet",
            "Hazy's Bar & Grill",
            "Lee's Hoagie House",
            "La Vera Pizzeria & Restaurant",
            "Don Giovanni's Classic Bakery",
            "Mythai Kitchen",
            "Stoli's Steaks",
            "Wings To Go - Feasterville, PA",
            "Cafe Madison Holland",
            "Baked by Michela",
            "Kyoto",
            "Kin Wha Garden",
            "Angela's Pizza 2",
            "Andalé Latino Grill",
            "Five Guys",
            "Bruster's Real Ice Cream",
            "Randevu Restaurant",
            "Johnny G’s Famous Pizza & Tomato ...",
            "Bobby O'S Deli",
            "Angelo's Pizzeria & Family Restaura...",
            "Angelo's",
            "House of Ph���",
            "Pho Palace",
            "Newportville Inn",
            "Carrabba's Italian Grill",
            "Red Robin Gourmet Burgers and B...",
            "Irish Rover Station House",
            "On The Border Mexican Grill & Canti...",
            "TGI Fridays",
            "Chickie's & Pete's",
            "La Hacienda Mexican Restaurant",
            "Cracker Barrel Old Country Store",
            "Shumai Wok",
            "Outback Steakhouse",
            "Metro Diner",
            "Liberty Bell Gastropub",
            "Parxgrill",
            "Langhorne Coffee House",
            "La Cena Ristorante",
            "Mirim Japanese And Korean Resta...",
            "Hong Kong Pearl",
            "Taps Sports Bar",
            "Philly Pretzel Factory",
            "Parx Beer Garden",
            "Bella Tori at the Mansion",
            "UNO Chicago Grill",
            "Brothers Pizza",
            "Steve's Prince of Steaks",
            "Denny's",
            "The Great American Diner and Pub a....",
            "Applebee's Grill + Bar",
            "Madison",
            "Wawa",
            "HF Hornberger Bakery",
            "New King Wok",
            "The Valley Pizza Restaurant",
            "The Langhorne Hotel",
            "Friendly's",
            "Chipotle Mexican Grill",
            "Pizza Pie II",
            "Langhorne Hotel Tavern & Restau...",
            "New Super Wok",
            "Burger King",
            "Fritz's Bakery",
            "Plum Tree Garden",
            "Bambu",
            "Taranovas",
            "The Cafe of Langhorne",
            "Coffee Cup Cafe",
            "LongHorn Steakhouse",
            "Thai Chef and Noodle Fusion",
            "Panera Bread",
            "Durham Delicatessen",
            "las margaritas mexican restaura...",
            "Three Monkeys Cafe",
            "The Dining Car",
            "Kelly's Seafood",
            "Miller's Ale House",
            "Macaroni's Restaurant",
            "Nifty Fifty's (Northeast Philadelph...",
            "Chickie's & Pete's",
            "Jinjin restaurant",
            "Tuscany Ristorante",
            "Liberty Bell Diner",
            "Benny The Bum's",
            "Emperor Restaurant | Wedding and Ev...",
            "Gallo's Seafood",
            "Crafty's Taproom",
            "Menchie's Frozen Yogurt",
            "The Union Tap",
            "Reedy's Tavern",
            "Jimmy's Timeout Sports Pub",
            "Steve's Prince of Steaks",
            "Joe Santucci's",
            "Little Caesars",
            "Curley's Pub",
            "Taco Bell",
            "Taste King",
            "Buffalo Wild Wings",
            "Dagwood's Pub",
            "Chick-fil-A",
            "Mission BBQ",
            "Red Lobster",
            "Royal Passage",
            "Brick House Bar & Grill",
            "No. 1 China",
            "Randi's Restaurant and Bar",
            "Paddy Whacks Irish Sports Pub - Wel...",
            "Mediterranean 2000",
            "IHOP",
            "Applebee's Grill + Bar",
            "Linden Italian Market",
            "To-Kai Japanese Restaurant",
            "Shtetl Kosher Restaurant",
            "George's Wings",
            "Originals Italian Restaurant & ...",
            "Olive Garden Italian Restaurant",
            "Marcello's Pizza Grill Philly",
            "Taste Queen Chinese Restaurant",
            "Andonios Diner",
            "Chipotle Mexican Grill",
            "Kabobi",
            "Asian Thai & Chinese Cuisine",
            "Texas Roadhouse",
            "Saladworks",
            "Golden Dawn Diner",
            "Georgine’s",
            "Eddington House",
            "Sunrise Diner",
            "Dave & Buster's Philadelphia - Fran...",
            "Golden Corral Buffet & Grill",
            "KPOT Korean BBQ & Hot Pot",
            "Sakura Japanese Restaurant",
            "Grand China Buffet",
            "The Fresh Works",
            "Crafty Crab",
            "Chili's Grill & Bar",
            "Shogun Japanese Hibachi & Sushi",
            "Bensalem Township Country Club",
            "Old Croydon Cafe",
            "Belly Busters",
            "Panera Bread",
            "Dom's Seafood",
            "Apollo's Family Pizzeria",
            "Club House Diner",
            "Vincenzo's Pizza",
            "Original Apple Pizza",
            "Vincenzo's",
            "The Deli & Pizza Shop",
            "Asian Chopsticks",
            "Riverboat Inn",
            "Curran's Irish Inn Restaurant",
            "King's China",
            "Place One Restaurant",
            "Burger King",
            "A & S Bagels",
            "Shagun Palace",
            "Little Tokyo",
            "7-Cup",
            "The Greater Knead",
            "Burger King",
            "Honest",
            "Panda Garden",
            "Lee's Hoagie House",
            "Riccardo's Pizza & Restaurant",
            "Giovanni’s Dillicious Pickles",
            "Lou's Deli",
            "Hong Kong Star Noodle House",
            "Spice Rack",
            "Wawa",
            "Boston Market",
            "Delicious Dishes Nj",
            "Asian Halal Meat Market",
            "Max's Steaks",
            "China House",
            "China Bowl",
            "Sals Seafood",
            "Yummy Garden",
            "Vernie's Soul Food Inc",
            "Temple Rainbow",
            "Blazin Flavorz Inc",
            "Tang’s Halal Chinese Restaura...",
            "New Wong House",
            "Sunny's Breakfast & Seafood",
            "D's Caribbean And American Food",
            "Attic Brewing Company",
            "Campus Pizza Restaurant",
            "Circles Bar",
            "Clock Bar",
            "New York Deli",
            "Tashia's Cocktails and Cuisine",
            "QDOBA Mexican Eats",
            "TimeOut Sports Bar",
            "New Barber's Hall",
            "Wingstop",
            "Lou & Choo's Lounge",
            "Subway",
            "Sid Booker's Shrimp Corner",
            "Paprika",
            "caribbean feast",
            "Saffron Indian Cuisine",
            "Coffeeland",
            "King Of Pizza",
            "Philly's Breakfast & Steaks",
            "Erie Square Restaurants",
            "The Bagel Hut",
            "Golden Dragon",
            "Tai's Vietnamese Food",
            "Hong Kong Star",
            "Bizini's Famous Steaks, Seafood and...",
            "Dwight's Southern Barbecue",
            "Lee's Breakfast",
            "Two Brothers Pizza",
            "China House",
            "Tropical Smoothie Cafe",
            "Pita Chip",
            "Number 1 Kitchen",
            "Happy Garden",
            "Allegheny",
            "DA FAMLY CAFE",
            "Gold Fish Chinese Restaurant & Seaf...",
            "Sun Happy Breakfast",
            "Wayne & Berkley Seafood",
            "El Balconcito",
            "Tacconelli's Pizza",
            "Czerw's Polish Kielbasa",
            "Tio Pepe",
            "Chickie's & Pete's",
            "Casa Brazil Steakhouse",
            "The Grey Lodge Pub",
            "Popeyes Louisiana Kitchen",
            "George's Lunchette",
            "Subway Imperial Plaza Shopping Cent...",
            "East Coast Wings + Grill",
            "Picanha Brazilian Steakhouse",
            "The Crazy Leprechaun",
            "Donna's Bar",
            "Rib Rack",
            "Leandro's Pizza House",
            "Bonk's Bar",
            "Philly Pretzel Factory",
            "Gaul & Co. Malt House Port Rich...",
            "Red Central Chinese Restaurant",
            "King Wok",
            "Spanish Island Restaurant",
            "Wawa",
            "Caf�� Mi Quang",
            "Popeyes Louisiana Kitchen",
            "Kitty's Luncheonette",
            "Aramingo's Best Pizza",
            "Burger King",
            "Salmon Beer Distribution",
            "Johnnie's Italian Restaurant",
            "Angelo's Pizza House",
            "E-Z Brunch",
            "Wawa",
            "Mr. Wish USA",
            "Super Garden",
            "Debbie's Place",
            "Lien's Restaurant",
            "Wawa",
            "New Azaad Foods",
            "Bambu",
            "Big Garden Restaurant",
            "Zemzem Halal Live Poultry , Viv...",
            "El Sabor De Baro",
            "Rico Mexican Tacos",
            "Port Richmond Pub",
            "Mi Rancho Mexican Grill",
            "Tay's Soul Food",
            "Pho Saigon",
            "Boston Market",
            "Krakus Market",
            "Buddakan",
            "Tony Luke's",
            "Jim's South St.",
            "Brauhaus Schmitz",
            "Morimoto",
            "Bistrot La Minette",
            "Fat Salmon Sushi",
            "Red Owl Tavern",
            "Royal Tavern",
            "LaScala���s Fire - Philly",
            "Tattooed Mom",
            "Lorenzo & Son Pizza",
            "Famous 4th Street Delicatessen",
            "Termini Bros Bakery",
            "Little Fish BYOB",
            "Marrakesh Restaurant",
            "Grindcore House",
            "Ishkabibble���s",
            "Le Pain Quotidien",
            "El Fuego",
            "Craftsman Row Saloon",
            "OREGON DINER",
            "Talula's Daily",
            "South Street Souvlaki",
            "Fitzwater Cafe",
            "Sushi Planet - Philly",
            "Talula's Garden",
            "Independence Beer Garden",
            "Cucina Forte",
            "Tortilleria San Roman",
            "Pretty Girls Cook",
            "Pho Ha Saigon",
            "O'Neals Pub",
            "Mifflin Tavern",
            "Kyoto Japan",
            "Saloon Restaurant",
            "Ba Le Bakery",
            "Reef Restaurant & Lounge",
            "Zouq Chicken And Smoothies",
            "Moonshine Philly",
            "John's Water Ice",
            "Zio Pizza Palace & Grill",
            "Frangelli's Bakery & Donuts",
            "Alyan's Middle Eastern & Mediterran...",
            "Southwark Restaurant",
            "Lovash Indian Cuisine & Bar",
            "Philly Cannoli King",
            "12 Steps Down",
            "Ice Max",
            "Iztaccihuatl Restaurant",
            "Frankford Hall",
            "John's Roast Pork",
            "Chart House",
            "Dave & Buster's Philadelphia",
            "The Kitchen Consigliere",
            "The Pop Shop Collingswood",
            "Sagami Japanese Restaurant",
            "Il Fiore",
            "Fette Sau",
            "Zeppoli",
            "The PUB",
            "Medusa Pizzeria",
            "Miguelina's Bakery",
            "Market Street Pizzeria & Italian Bi...",
            "LongHorn Steakhouse",
            "La Hacienda",
            "Mainstay Independent Brewing Co...",
            "Corinne's Place",
            "Ekta Indian Cuisine",
            "Johnny Brenda's",
            "Barcade",
            "Donkey's Place",
            "Benihana",
            "Sabrina's Cafe @ Powelton",
            "Osaka",
            "La Colombe Coffee Roasters",
            "Old San Juan Restaurant",
            "SAPORI TRATTORIA ITALIANA",
            "Yards Brewing Company",
            "Nunzio Ristorante Rustico",
            "Kraftwork",
            "Murph's Bar",
            "Bottle Bar East",
            "Interstate Drafthouse",
            "Applebee's Grill + Bar",
            "La Cocina, Pennsauken",
            "hearthside",
            "Millies Kitchen",
            "3 J���s Food Market Fishtown",
            "Tortilla Press",
            "Villa Barone",
            "Boston Market",
            "Miller's Ale House",
            "Bistro di Marino",
            "Riccardo's Pizza",
            "Philadelphia Distilling",
            "Krispy Krunchy Chicken",
            "Joe's Steaks + Soda Shop",
            "Wild Wings Pizza & Grill",
            "Indiya - Flavors Of India",
            "Sweet Lucy's Smokehouse",
            "Due Amici Italian Grill",
            "Sweetwater Bar & Grill",
            "Ashburner Inn",
            "Pandora 2 Diner",
            "Double Nickel Brewing Company",
            "Mayfair Diner",
            "Kung Fu Tea",
            "Kennedy Chicken & Kebab",
            "Tarimas",
            "Holmesburg Bakery",
            "Cappy's Cafe",
            "House of Thai Cuisine",
            "Al's Corner Deli and Catering Servi...",
            "Harrington's Pub",
            "Hibachi Grill & Supreme Buffet",
            "New Station Pizza IV",
            "Kings Highway Tavern",
            "Juanita's Mexican Cuisine",
            "Tokyo Bleu",
            "Milanese Pizza - Riverton, NJ",
            "Wawa",
            "Castle Harbor Drive-in",
            "Tate's Good Food Restaurant",
            "Sumo Sushi",
            "Wawa",
            "Breakfast Nook Cafe",
            "Panda Chinese Restaurant",
            "Happy Wok Chinese Restaurant",
            "Whistlers Inn",
            "Zaccone's Restaurant",
            "Dragon Phoenix House",
            "The Jug Handle Inn",
            "Athenian Restaurant",
            "Friendly's",
            "Smoothie King",
            "Zio's Tuscan Grille",
            "Georgetti's Pasta & Sauce",
            "Jean's Pizza & Grill",
            "Sweeties & Cream",
            "Shef's Pizza & Deli",
            "Zena's Bakery And Cafe",
            "The Soup Bar",
            "Wild Flour Bakery",
            "Baba Grill",
            "Maggie's Waterfront Cafe",
            "Saladworks",
            "CHINA RAINBOW RESTAURANT",
            "Chop Cheese Restaurant & Lounge",
            "Jack's Place",
            "Red Lobster",
            "Gaetano's Steaks",
            "Rt. 130 Diner",
            "Dooney's Pub Delran",
            "L & M Bakery",
            "The Madison",
            "Crab Du Jour",
            "Jersey Mike's Subs",
            "Taco Bell",
            "Crawford's Corner Bar & Kitchen",
            "Franco's Taqueria",
            "Guilli's Authentic Mexican Cuisine ...",
            "Best of the Wurst",
            "Pecado Colombiano",
            "Angelo's Pizza",
            "Supremos",
            "Lili's Café",
            "Johnny G's",
            "Starbucks",
            "Arnieri's Pizzeria",
            "Arby's",
            "McDonald's",
            "Ott's Tavern",
            "Delran Bagel Cafe",
            "Dunkin'",
            "Vid's Deli",
            "Holiday Ice Cream",
            "Towne Tavern",
            "Gaetano's Penny Packer",
            "On The Grill",
            "Pavilion Barbecue",
            "NO. 1 Chinese Restaurant",
            "Hungry Dog Grill",
            "Seafood Haven",
            "Starbucks",
            "Rams Deli Riverside Nj",
            "White Eagle Liquor",
            "PrimoHoagies",
            "Maebellscakeadventure",
            "Cafe Darota",
            "RIVERSIDE BARBECUE",
            "Saladworks",
            "Crystal Diner",
            "Hartford Market",
            "Burger King",
            "Alfredo's Brazilian Steakhouse",
            "Beer Factory",
            "Chez Rodine Caribbean Restaurant",
            "De Luca's Bakery",
            "Yum Yum Asian Fusion",
            "The Pour House - Westmont",
            "Maggiano's Little Italy",
            "The Cheesecake Factory",
            "Ponzio's Diner-Bakery-Bar",
            "Seasons 52",
            "The Capital Grille",
            "Yokohama Japanese Restaurant",
            "Iron Hill Brewery and Restaurant",
            "Dolsot House | K-Town BBQ Korean Re...",
            "Bahama Breeze",
            "Silver Diner",
            "Caffe Aldo Lamberti",
            "Bistro at Cherry Hill",
            "Brio Italian Grille",
            "Kabuki Japanese Cuisine",
            "Tortilla Press Cantina",
            "IHOP",
            "First Watch",
            "Indeblue Modern Indian",
            "Goodbeet",
            "Saladworks",
            "Normas Mediterranean and Middle Eas...",
            "Franco's Place",
            "UNO Pizzeria and Grill",
            "TGI Fridays",
            "TACCONELLI'S PIZZERIA",
            "Red Robin Gourmet Burgers and B...",
            "Red Lobster",
            "Steak 38",
            "The Melting Pot",
            "Keg & Kitchen",
            "Han Dynasty",
            "Mikado Japanese Restaurant",
            "Ming Garden Chinese Restaurant",
            "Maple Shade Custard Stand",
            "Rita's Italian Ice & Frozen Cus...",
            "Subway",
            "LongHorn Steakhouse",
            "Pizza Plaza Italian Eatery & Cateri...",
            "Chick-fil-A",
            "Amy's Omelette House",
            "Bobby Ray's Pennsauken Tavern",
            "Splitz Bar & Grill",
            "QDOBA Mexican Eats",
            "Sang Kee Noodle Cafe",
            "Panera Bread",
            "La Cita",
            "Eden Korean Restaurant",
            "Turning Point of Cherry Hill",
            "Outback Steakhouse",
            "Miller's Ale House",
            "Firebirds Wood Fired Grill",
            "The Kettle & Grille",
            "Megu Sushi Asian Cuisine",
            "Bob Evans",
            "Cracker Barrel Old Country Store",
            "Philly Soft Pretzel Factory",
            "Barone's Tuscan Grill",
            "Chili's Grill & Bar",
            "Kiri Udon",
            "Forgotten Boardwalk Brewing Com...",
            "P.J. Whelihan's Pub + Restaurant - ...",
            "Joe Italiano's Maplewood",
            "Anthony's Coal Fired Pizza & Wi...",
            "Pho Xinh",
            "El Azteca Mexican Restaurant",
            "Buffalo Wild Wings",
            "Jay's Elbow Room",
            "Oriental Pearl- Moorestown",
            "Bhan Thai (Mt. Laurel)",
            "Boston Market",
            "Redz Restaurant",
            "Asian Chef Fusion Cuisine",
            "Maurizio's Bistro",
            "Applebee's Grill + Bar",
            "Pancheros Mexican Grill - Mount Lau...",
            "Scotto's pizza marlton",
            "Healthy Garden & Gourmet Pizza",
            "Akira moorestown",
            "Carollo's Little Italy",
            "Ruby Tuesday",
            "Moe's Southwest Grill",
            "Chipotle Mexican Grill",
            "Jersey Mike's Subs",
            "Daddy O's Homemade Ice Cream",
            "Angelo's Pizza",
            "Sushi to Go",
            "Shanghai Express Chinese Food",
            "Philly Pretzel Factory",
            "Chick-fil-A",
            "Cathy's Carryout Cuisine",
            "Naan Indian Bistro",
            "Talia's Restaurant & Bar",
            "Black's Blues",
            "La Vita's Pizzeria",
            "Passariellos Pizzeria & Italian Kit...",
            "Panera Bread",
            "On The Border Mexican Grill & Canti...",
            "Panera Bread",
            "Blue Fig Cafe"
        ]

        //Remove any duplicates
        names = Array.from(new Set(names));

        //Remove any characters that aren't letters, numbers, spaces, or punctuation
        names = names.map(name => name.replace(/[^a-zA-Z0-9\s.,;'"!?]/g, ''));


        let count = 0;

        await Promise.all(names.map(async (name) => {
            //make new page for each url

            await new Promise((res) => {
                setTimeout(() => {
                    let check = setInterval(() => {
                        console.log("check", count);
                        if (count < 10) {
                            res();
                            clearInterval(check);
                        }
                    }, 1000);
                }, Math.random() * 1000);
            })
            count++;

            console.log("past count");
            const newPage = await browser.newPage();
            newPage.setViewport({ width: 1536, height: 730 });

            await newPage.goto(`https://www.google.com/maps/search/${name}/@40.1926361,-75.1390561,17z?entry=ttu`, {
                timeout: 0
            });
            console.log("main wati");
            await newPage.waitForSelector("[role=main]", {
                timeout: 0
            });
            console.log("YEA");
            console.log(name);
            const redirect = await newPage.evaluate(() => {
                try {
                    const notPreciseEnough = !![...document.getElementsByTagName("span")].find(x => x.innerText === "You've reached the end of the list.");
                    if (notPreciseEnough) {
                        const firstUrl = [...document.querySelector("[role=main]").children[0].children[0].children].filter((x) => {
                            return [...x.classList].length == 0 && [...x.children].length > 0
                        })[0].children[0].children[0].href;
                        return firstUrl;
                    }
                } catch (e) {
                    return false;
                }
            });
            console.log(name, redirect);
            if (redirect) {
                console.log("direction on ", name, " to ", redirect);
                await newPage.goto(redirect, { timeout: 0 });
            }

            await newPage.waitForFunction('document.querySelector(".fontBodyMedium")', {
                timeout: 0
            });

            const webUrl = await newPage.evaluate(() => {
                const urlElement = document.querySelector(`[data-tooltip="Open website"]`);
                if (urlElement) {
                    return urlElement.children[0].children[1].innerText;
                } else {
                    return false;
                }
            });
            results[name] = webUrl;
            if (webUrl) {
                const ignoreStrings = ["facebook", "instagram"];

                ignoreStrings.forEach((string) => {
                    if (webUrl.includes(string)) {
                        results[name] = false;
                    }
                })
            }
            current++;
            console.log("CLSOING", name)
            count--;
            await newPage.close();
        }));


        done();

    }
    async function done() {
        const noSites = [];
        Object.keys(results).forEach((restaurant) => {
            if (!results[restaurant]) {
                console.log(`${restaurant}:           https://google.com/search?q=${encodeURIComponent(restaurant)} `);
                noSites.push(restaurant);
            }
        });

        const batchSize = 10;
        //Split noSites into batches of batchSize
        const batches = [];
        for (let i = 0; i < noSites.length; i += batchSize) {
            batches.push(noSites.slice(i, i + batchSize));
        }

        console.log("----------DONE-------------");
        //Iterate over batches with a delay of 10 seconds. For each item in batch, find contact points and add to an array if they exist
        const contactPoints = [];
        for (batch of batches) {
            for (var i = 0; i < batch.length; i++) {
                const restaurant = batch[i];
                const urls = await findContactPoints(restaurant, browser);
                if (urls.length > 0) {
                    contactPoints.push({
                        name: restaurant,
                        urls: urls
                    });
                    console.log(restaurant);
                    urls.forEach((url) => {
                        console.log(url);
                    });
                    console.log("----------");
                }
            }
            await new Promise(resolve => setTimeout(resolve, 10 * 1000));
        }
        browser.close();
    }
    scrapeCurrentURLs();
})();